"""initial

Revision ID: c02968ee91b4
Revises: 
Create Date: 2026-01-30 20:11:03.163144

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02968ee91b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ceipal_batch_run',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('request_json', sa.Text(), nullable=True),
    sa.Column('jobs_processed', sa.Integer(), nullable=True),
    sa.Column('candidates_selected', sa.Integer(), nullable=True),
    sa.Column('messages_attempted', sa.Integer(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ceipal_batch_run_id'), 'ceipal_batch_run', ['id'], unique=False)
    op.create_table('ceipal_job_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_code', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('job_status', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('score_threshold', sa.String(length=50), nullable=True),
    sa.Column('total_candidates', sa.Integer(), nullable=True),
    sa.Column('selected_candidates', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ceipal_job_run_id'), 'ceipal_job_run', ['id'], unique=False)
    op.create_index(op.f('ix_ceipal_job_run_job_code'), 'ceipal_job_run', ['job_code'], unique=False)
    op.create_table('ceipal_candidate_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_run_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.String(length=255), nullable=True),
    sa.Column('candidate_name', sa.String(length=255), nullable=True),
    sa.Column('candidate_email', sa.String(length=255), nullable=True),
    sa.Column('candidate_phone', sa.String(length=50), nullable=True),
    sa.Column('score', sa.String(length=50), nullable=True),
    sa.Column('sms_status', sa.String(length=50), nullable=True),
    sa.Column('email_status', sa.String(length=50), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_run_id'], ['ceipal_job_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ceipal_candidate_run_candidate_id'), 'ceipal_candidate_run', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_ceipal_candidate_run_id'), 'ceipal_candidate_run', ['id'], unique=False)
    op.create_index(op.f('ix_ceipal_candidate_run_job_run_id'), 'ceipal_candidate_run', ['job_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ceipal_candidate_run_job_run_id'), table_name='ceipal_candidate_run')
    op.drop_index(op.f('ix_ceipal_candidate_run_id'), table_name='ceipal_candidate_run')
    op.drop_index(op.f('ix_ceipal_candidate_run_candidate_id'), table_name='ceipal_candidate_run')
    op.drop_table('ceipal_candidate_run')
    op.drop_index(op.f('ix_ceipal_job_run_job_code'), table_name='ceipal_job_run')
    op.drop_index(op.f('ix_ceipal_job_run_id'), table_name='ceipal_job_run')
    op.drop_table('ceipal_job_run')
    op.drop_index(op.f('ix_ceipal_batch_run_id'), table_name='ceipal_batch_run')
    op.drop_table('ceipal_batch_run')
    # ### end Alembic commands ###
